
EXECUTABLE_SUFFIX=.exe
OBJECT_SUFFIX=.obj
REMOVE_FILE=del
DIRECTORY_SEPARATOR=\\

.SUFFIXES:$(EXECUTABLE_SUFFIX) $(OBJECT_SUFFIX) .c

.c$(OBJECT_SUFFIX):
	cl $** /Fo$@ /nologo /Wall /c

$(OBJECT_SUFFIX)$(EXECUTABLE_SUFFIX):
	cl $** /Fe$@ /nologo /link

include Makefile.inc

